### ISSUE TITLE
can't build relocatable plugins

### ISSUE THREAD

**Issue by jmarino** [LLNL/yorick#28]
I was trying to build relocatable plugins by running the following commands (as regular user):

    yorick -batch make.i
    make
    DESTDIR="my_local_path" make install

The install phase fails when it tries to write directly to `/usr` instead of `my_local_path/usr`. 
I found that the plugins that suffered from this problem had these lines in their `Makefile`:

    include $(Y_MAKEDIR)/Make.cfg
    include $(Y_MAKEDIR)/Makepkg
    include $(Y_MAKEDIR)/Make$(TGT)

The problem seems to be caused by yorick's `Makepkg` always clearing the value of `DESTDIR`. I was able to build relocatable plugins by applying the following patch to yorick:

    diff --git a/Makepkg b/Makepkg
    index 5837a00..396cf0e 100644
    --- a/Makepkg
    +++ b/Makepkg
    @@ -172,7 +172,6 @@ dist: distclean
 
     Y_GROUP=`cat $(Y_LIBEXE)/install.grp`
     YNSTALL=$(Y_LIBEXE)/install.sh $(Y_GROUP)
    -DESTDIR=
     DEST_Y_SITE=$(DESTDIR)$(Y_EXE_SITE)
     DEST_Y_HOME=$(DESTDIR)$(Y_EXE_HOME)
     DEST_Y_BINDIR=$(DESTDIR)$(Y_BINDIR)

**Comment by dhmunro** [comment]
Note that yorick is obsolete.  Please use scipy (scipy.org), with the npplus package from pypi.org and the qnd package from github.com/LLNL/qnd for legacy yorick compatibility.
