### ISSUE TITLE
distrib/yorick.spec - %preun install-info failing on uninstall.

### ISSUE THREAD

**Issue by pellucida** [LLNL/yorick#32]
On a RHEL7.9 platform the package built with the spec file
yorick-2.2/distrib/yorick.spec with
```
%preun
if [ "$1" = "0" ] ; then # last uninstall
 if [ -x /sbin/install-info ]; then
   /sbin/install-info --delete yorick %{_datadir}/info/dir
 fi
fi
```
fails when uninstalling (use instead: rpm -e --noscripts yorick )
The install-info command that appears to be required is
```
/sbin/install-info --delete %{_datadir}/info/yorick.info.gz %{_datadir}/info/dir
```
Patch is attached
[yorick-patch.txt](https://github.com/LLNL/yorick/files/5676616/yorick-patch.txt)

**Comment by dhmunro** [comment]
This is a very old version of yorick.  Please use the version in this github repo.

Also, note that yorick is obsolete.  You should use scipy (scipy.org).  The npplus python package at pypi.org and the qnd package at github.com/LLNL/qnd can help with legacy yorick compatibility.
