### ISSUE TITLE
Undefined symbols for architecture x86_64

### ISSUE THREAD

**Issue by youcefbo** [LLNL/yorick#33]
Hi,
I am trying to install Yorick on macOS Catalina but the installation fails. When I run the Make install command I get this error:

```
Undefined symbols for architecture x86_64:
  "_exp10", referenced from:
      _NiceAdjust in libgist.a(draw.o)
      _GdGetLimits in libgist.a(draw.o)
      _GpNiceUnit in libgist.a(tick.o)
      _ScopeOutTicks in libgist.a(tick.o)
      _FindTicks in libgist.a(tick.o)
ld: symbol(s) not found for architecture x86_64 
collect2: error: ld returned 1 exit status
make[1]: *** [gist] Error 1
make: *** [gistexe] Error 2
```
Is there a way to fix this issue?
Thank you.

**Comment by dhmunro** [comment]
FIrst, yorick is obsolete and I strongly recommend you use scipy (scipy.org) instead.  There are some yorick-like functions for python available in the npplus package at PyPI ([https://pypi.org/project/npplus/]) and you can use the QnD package at [https://github.com/LLNL/qnd] to access binary files (like netCDF or HDF5) with a yorick-like API.

MacOS X diverges farther and farther from UNIX, and you will probably need to tinker with your X Code installation to bring it back into conformance with the POSIX standards yorick uses for its configuration scripts.  If you type "make distclean" then "make config", yorick will configure itself and print out a lot of details about what it found.  Fairly far down that output, you will find a section "begin yorick configuration".  This is the output from the execution of the script yorick/yconfig.sh.  A part of that output is going to read "using exp10 found in libm", which means that the script has successfully built a test binary that calls the standard math library function exp10.  You will need to compare the compiler flags that test script used and compare those to the final compile flags passed during the yorick load to try to understand why the load flags passed during configure worked while the flags passed during the final build did not.  If you want to think less, you can simply go into the Make.cfg script produced by configure and change the NO_EXP10 line to "NO_EXP10=-DNO_EXP10" to include a non-standard library implementation of exp10.  But if your configuration is messed up there, it might be messed up elsewhere as well.
