### ISSUE TITLE
Update homepage

### ISSUE THREAD

**Issue by ryandesign** [LLNL/yorick#34]
The homepage of this GitHub repo is listed as:

https://yorick.github.com

*.github.com project web site links no longer work. You must update this to:

https://yorick.github.io

**Comment by ryandesign** [comment]
There are also links to the outdated URL in the README, maybe elsewhere.

**Comment by VictorelPetrovich** [comment]
https://yorick.github.io/ doesn't work either

**Comment by dhmunro** [comment]
The issue should be moved to the yorick-doc repo, which is what generates the github pages for yorick.  The pages would then show up at llnl.github.io/yorick, except that llnl.github.io has been set up to redirect to software.llnl.gov, so none of the github pages for repos of the LLNL user is likely to work.  I no longer can change the yorick-doc project settings, so I can't fix this or even work on it.  You'll need to find someone who can administer the yorick-doc repo.

**Comment by ryandesign** [comment]
> https://yorick.github.io/ doesn't work either

It [did work when I filed this ticket 18 months ago](https://web.archive.org/web/20210724131636/https://yorick.github.io). Not my fault someone broke it since then.

> The issue should be moved to the yorick-doc repo,

No. The homepage *of this GitHub repo* is listed as `https://yorick.github.com/` which [doesn't work](https://web.archive.org/web/20211026143542/http://yorick.github.com/). Change it to something that does work.

I am not involved with the yorick project and won't jump through any further hoops in reporting this problem. Your project, you figure it out.

**Comment by dhmunro** [comment]
Yorick has transitioned to legacy code, which means it is either unsupported or only supported when internal LLNL users require a change.  You should not be writing new yorick code unless you support yorick yourself.  Use scipy (python+numpy+scipy) instead, which can do everything yorick could do with roughly the same performance.  If you need to combine legacy yorick programs with new python code, you can use the LLNL/pyorick repo to run yorick as a subprocess of python, which enables you to port old yorick code one piece at a time.  If you need to read old yorick binary files you can use the LLNL/qnd repo.

Given this status, getting a live webpage working for the yorick documentation tree is a very low priority and may never happen.  You can build the tree from the LLNL/yorick-doc repo if you desperately need the documentation for an obsolete programming language, but I urge you not to spend any significant time studying it.  You can also build the documentation for individual yorick packages from their doc directories (e.g.- the doc directory in this yorick repo) when you build the code.  An extremely old version of the homepage is live online at yorick.sourceforge.net (yorick version 1.1? - final version was 2.2.04).

The github.com/emmt/yeti repo apparently still has some support, but that may not extend to building yorick-doc.

I'm sorry I suggested you move the issue to the LLNL.yorick-doc repo; I agree you shouldn't spend any more time on this.  I went ahead and put a note there as well.

If someone who can change the settings of this project reads this, you should remove the broken homepage as ryandesign suggests.
